# Generated by Django 4.2.8 on 2023-12-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='Categories', to='catalog.category'),
        ),
    ]
