# Generated by Django 4.2.8 on 2023-12-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, null=True)),
                ('image', models.ImageField(height_field='height', upload_to='images/', width_field='width')),
                ('width', models.IntegerField(editable=False)),
                ('height', models.IntegerField(editable=False)),
                ('file_hash', models.CharField(db_index=True, max_length=40)),
                ('file_size', models.PositiveIntegerField(null=True)),
                ('focal_points_x', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_points_y', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_points_width', models.PositiveIntegerField(blank=True, null=True)),
                ('focal_points_height', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
